### ISSUE TITLE
Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by horizon-z40** [cvfish/PangaeaTracking#8]
hello,There was an error about  ´ Segmentation fault      (core dumped) ´ when I run your example, Yiwan.sh,Can you tell me how to fix it?

**Comment by cvfish** [comment]
Hi, I've fixed the bug. You could pull the new code and try again.

**Comment by ptueller** [comment]
Hello, I'm still getting an error with the current code. It prints out "../results/yiwan_test_trust_region/" and then segmentation faults.
